version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://mongo:27017
      DATABASE_NAME: interview_platform
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - b5c581e2e7183ea722b9499bf9aae17ff9603cc87fdaf38304580d35e7a62a88:/data/db

volumes:
  b5c581e2e7183ea722b9499bf9aae17ff9603cc87fdaf38304580d35e7a62a88:
    external: true

