version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://mongo:27017
      DATABASE_NAME: interview_platform
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      HTTP_REFERER: ${HTTP_REFERER}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
